export default () => ({
    PORT: process.env.PORT || 5000,
    NODE_ENV: process.env.NODE_ENV,
    BASE_URL: process.env.BASE_URL,
    SECRET_KEY: process.env.SECRET_KEY,
    JWT_REFRESH_TOKEN_SECRET: process.env.JWT_REFRESH_TOKEN_SECRET,
    JWT_REFRESH_TOKEN_EXPIRATION_TIME: process.env.JWT_REFRESH_TOKEN_EXPIRATION_TIME,
    ENCRYPTION_KEY: process.env.ENCRYPTION_KEY,
    FLW_PUBLIC_KEY: process.env.FLW_PUBLIC_KEY,
    FLW_SECRET_KEY: process.env.FLW_SECRET_KEY,
    FLW_ENCRYPTION_KEY: process.env.FLW_ENCRYPTION_KEY,
    DB_HOST: process.env.DB_HOST,
    DB_PORT: process.env.DB_PORT,
    DB_USERNAME: process.env.DB_USERNAME,
    DB_PASSWORD: process.env.DB_PASSWORD,
    DB_DATABASE: process.env.DB_DATABASE,
    DB_URI: process.env.DB_URI,
    RANDOM_IV: process.env.RANDOM_IV,
    AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
    AWS_SECURITY_KEY: process.env.AWS_SECURITY_KEY,
    AWS_BUCKET_NAME: process.env.AWS_BUCKET_NAME,
    emailRegex:
      /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/,
    // FLW_PUBLIC_KEY: process.env.FLW_PUBLIC_KEY,
    // FLW_SECRET_KEY: process.env.FLW_SECRET_KEY,
});